#!/usr/bin/env bash
#
# Turn the camera originals in images/ into what the album actually serves:
#
#   photos/NN.webp          the page image, longest side 1600px
#   photos/thumbs/NN.webp   the contents grid, longest side 320px
#   assets/js/photos.js     the manifest, with a base64 blur-up per photograph
#
# The originals here are ~60 megapixels and up to 130 MB each, so this is not
# optional — it is the difference between a 4.6 MB album and a 1.7 GB one.
#
# Reads the running order from tools/order.txt. Needs `sips` (ships with macOS)
# and `cwebp` (brew install webp).
#
# Usage:  ./tools/build-photos.sh

set -euo pipefail

cd "$(dirname "$0")/.."

SRC_DIR="images"
OUT_DIR="photos"
THUMB_DIR="$OUT_DIR/thumbs"
MANIFEST="assets/js/photos.js"
ORDER="tools/order.txt"

PAGE_MAX=1600      # longest side of a page image
THUMB_MAX=320      # longest side of a contents thumbnail
LQIP_MAX=20        # longest side of the inline blur-up
PAGE_Q=82
THUMB_Q=72
LQIP_Q=45

for tool in sips cwebp; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "error: '$tool' not found." >&2
    [ "$tool" = "cwebp" ] && echo "  install it with: brew install webp" >&2
    exit 1
  }
done

[ -f "$ORDER" ] || { echo "error: $ORDER not found." >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

rm -rf "$OUT_DIR"
mkdir -p "$THUMB_DIR" "$(dirname "$MANIFEST")"

echo "window.WEDDING_PHOTOS = [" > "$TMP/body"

count=0
missing=0

while IFS='|' read -r file chapter caption alt; do
  # Skip comments and blank lines.
  case "$file" in ''|'#'*) continue ;; esac

  if [ ! -f "$SRC_DIR/$file" ]; then
    echo "  ! missing: $file" >&2
    missing=$((missing + 1))
    continue
  fi

  count=$((count + 1))
  n=$(printf "%02d" "$count")

  # sips cannot read webp, so every derivative comes off the original JPEG.
  sips --resampleHeightWidthMax "$PAGE_MAX" "$SRC_DIR/$file" \
       --out "$TMP/page.png" >/dev/null 2>&1
  cwebp -q "$PAGE_Q" -m 6 -quiet "$TMP/page.png" -o "$OUT_DIR/$n.webp"

  sips --resampleHeightWidthMax "$THUMB_MAX" "$SRC_DIR/$file" \
       --out "$TMP/thumb.png" >/dev/null 2>&1
  cwebp -q "$THUMB_Q" -quiet "$TMP/thumb.png" -o "$THUMB_DIR/$n.webp"

  sips --resampleHeightWidthMax "$LQIP_MAX" "$SRC_DIR/$file" \
       --out "$TMP/lqip.png" >/dev/null 2>&1
  cwebp -q "$LQIP_Q" -quiet "$TMP/lqip.png" -o "$TMP/lqip.webp"

  # Orientation drives the page layout: portraits fill the page edge to edge,
  # landscapes are mounted on the paper with a mat.
  w=$(sips -g pixelWidth  "$TMP/page.png" | tail -1 | awk '{print $2}')
  h=$(sips -g pixelHeight "$TMP/page.png" | tail -1 | awk '{print $2}')
  if [ "$w" -gt "$h" ]; then o="landscape"; else o="portrait"; fi

  lqip=$(base64 -i "$TMP/lqip.webp" | tr -d '\n')

  esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

  {
    printf '  { id: %d, src: "%s/%s.webp", w: %s, h: %s, o: "%s"' \
           "$count" "$OUT_DIR" "$n" "$w" "$h" "$o"
    [ -n "${chapter:-}" ] && printf ', chapter: "%s"' "$(esc "$chapter")"
    [ -n "${caption:-}" ] && printf ', caption: "%s"' "$(esc "$caption")"
    [ -n "${alt:-}" ]     && printf ', alt: "%s"'     "$(esc "$alt")"
    printf ', lqip: "data:image/webp;base64,%s" },\n' "$lqip"
  } >> "$TMP/body"

  printf '\r  %s  %s' "$n" "$file"
done < "$ORDER"

echo "];" >> "$TMP/body"

{
  echo "/* Generated by tools/build-photos.sh — edit tools/order.txt instead. */"
  cat "$TMP/body"
} > "$MANIFEST"

printf '\r\033[K'
echo "built $count photographs -> $OUT_DIR ($(du -sh "$OUT_DIR" | cut -f1))"
[ "$missing" -gt 0 ] && echo "warning: $missing file(s) in $ORDER were not found in $SRC_DIR/" >&2
exit 0
